---
title: "Intro"
documentclass: article
output: 
  bookdown::pdf_document2:
    number_sections: yes 
    fig_caption: yes        
    includes:
      in_header: "preamble.tex"
papersize: a4
bibliography: ties.bib
biblio-style: apa
---


# Introduction {#sec1}
Inflation and inflation controlling are a matter of public concern in countries across the globe as they increase prices and deny access for consumption to the masses. Crude oil and food are two inevitable components in economic development and the basic life of people. The unprecedented fluctuations in the prices of these will have serious implications on energy and food security for any country. For common people, their income fails to increase with changes in prices always, which limits their consumption. On a macro level, fluctuations in the prices of oil and food will have repercussions on the employment rate, interest rate, inflation rate, and economic growth of a country, thus in both ways, the dynamics of these prices are a concern for policymakers. Determinants of inflation and its facets show the transition in India, especially after the global financial crisis [@Mohanty2015]. The heavy reliance of the Indian economy on international markets for its oil requirements makes domestic prices sensitive to changes in international oil prices [@RePEc:ess:wpaper:id:4319]. In oil-importing countries, it is practically impossible to eliminate the detrimental role of energy prices in economic growth [@Shahbaz2017]. The administrative oil prices regime in India played the role of shock absorber for a long time. The objectives of such a system were to safeguard the public from the direct impact of oil price hikes in international markets. But this mechanism could only ensure postponement of inflationary pressures which subsequently realized [@Bhattacharya2001]. Later this system was lifted and thus price changes in the international market started reflecting in domestic prices. The impact of increased oil prices is not homogenous across the countries. The effects will be deeper in developing countries than in developed countries. The inadequate oil-conservation techniques and oil dependence of the production process in these countries are considered as the reasons for this imbalance [@Bhattacharya2001; @Varghese2017]. 
The increase in crude oil prices will influence the economy in multiple ways. An increase in energy bills of households, industry, and government as they are direct consumers of oil may end up in a slowdown of consumption expenditures in the economy. Changes in oil prices may have direct and indirect effects on the aggregate level of output, affecting investment in production and other economic activities [@KHRAIEF2021125423]. This will work as a rise in the unit cost of production for industries and agriculture [@Tang2010]. These changes will be ultimately visible on productivity, real wages and employment, selling prices, core inflation, profits, and investment in the economy. The empirical estimation using econometric models has revealed that the impact of crude oil prices on economic variables is not homogeneous [@bhattacharyaFuelPricingPolicy2009].For example, there are substantial differences and heterogeneities in the responses of the BRICS economies to oil prices shocks [@nasirImplicationsOilPrices2018]. Moreover, the repercussions of price hikes on economies depend on the level of economic development and position in world trade. In developing countries, food is a major component in the consumption basket, which makes food prices a major driver of general consumer prices in the country and affects the poor sections of a society deeply [@dasOilPriceShock2014; @Jongwanich2011]. Here the increase in oil price will couple with food prices and the joint effect on the economy will be greater [@alghalithInteractionFoodPrices2010]. Unexpected increases in oil prices are associated with high food prices due to the increased costs of processing, transportation, and distribution of food. The impact of oil prices on food prices also varies with the overland travel distance. High energy prices exert greater upward pressure on local food prices in those markets that are the farthest from coastal ports than on those markets that are at the port of entry due to increased transportation costs [@tiwariAnalyzingTimefrequencyLead2018].

And, on a global level, the majority of poor countries in the world are net food importers which makes them more affected by higher food prices [@ngFoodPriceIncreases2008]. Thus, for oil-importing poor and developing countries higher oil and fuel prices endanger their energy security and threaten their food security [@Taghizadeh-Hesary2019].


The heterogeneity in the impact of oil prices on world economies motivated wide research on the fuel-food co-movement. The history of researches on the co-movement shows that the context of each study was different for different countries and times. The theoretical and empirical studies primarily brought explanations to the link between energy and agricultural commodities and then draw further conclusions on their behavior. In the case of India, the most relevant conclusion on the tradeoff between oil and food prices is based on the Cost-push hypothesis. Even though in the literature, empirical evidence for other rationales viz based on higher demand for biofuels, effects of general inflation, and recent financialization are also prominent, but their relative significance is limited in the Indian context. According to this, the conventional transmission mechanism, oil prices significantly affect the production cost of agricultural outputs and thus food prices [@bafes2007; @Esmaeili2011; @hansen1993; @Taghizadeh-Hesary2019; @Goh2020] which will pass to the final prices. Oil and oil derivatives are used in primary and secondary stages of agricultural production in various factors. Considering the supply side, changes in oil prices will have its impact on the cost of these factors. Generally, inflation in India had stayed at an average of 6.7 percent for a period from 1950 to 2013 which shows that WPI inflation is modest in the country [@Mohanty2015]. Different factors triggered the occurrences of high food inflation in India over the years. Recent trends in inflation are mainly explained in the literature focusing on demand-side factors [@Kumar2009; @Nair2012; @basu2011; @chand2010; @Kumar2009]. The strong inflationary pressure in the country especially since 2007 is well associated with a large share of food and fuel products in total consumption. The role of a cost-push supply shock in food prices, along with oil prices is considered critical in inflation in India [@dasOilPriceShock2014; @Holtemoller2016; @Nair2012]. 

Considering Oil prices as one of the key determinants of food inflation in India, there is a need for a meticulous assessment of the tradeoff between oil and food prices. The co-movement of oil prices and food inflation (and general inflation) has been assessed and addressed extensively for many economies in the world. In the Indian context, the relationship between food and oil prices has been well established with symmetric relationships, in the literature. This paper is an attempt to address the potential asymmetries in their behavior. A cointegration analysis of oil prices and food prices in India for the period 2012-2016 (monthly data) is the purpose of this paper. Using the newly introduced wholesale price index-based food index with the base year 2011-12 series along with WTI (Western Texas Intermediate) crude oil prices a non-linear autoregressive distributed lag (NARDL) model is proposed. Even though food and food-related items hold a significant share in both of the major indices used in measuring inflation in India, by using wholesale price index (WPI) monthly data, the study enables to analyze of food inflation from the supply side as WPI is considered as a producer’s index.  

The structure of the paper is as follows: Section \@ref(sec2) briefs the existing literature on the co-movement between oil prices and inflation. A description of data and methodology are discussed in Section \@ref(sec3). The empirical result and discussion are reported in Section \@ref(sec4). The conclusion with policy implications is drawn in Section \@ref(sec5) .

