---
title: "Intro"
documentclass: article
output: 
  bookdown::pdf_document2:
    number_sections: yes 
    fig_caption: yes        
    includes:
      in_header: "preamble.tex"
papersize: a4
bibliography: ties.bib
biblio-style: apa
---

# Review of literature {#sec2}
The relationship between energy and food prices has been analyzed extensively in the literature. There is a general conscience extracted from several studies regarding the influence of oil price movements on economic variables, which depends on multiple factors including the structure of the particular economy, energy intensity of sectors, etc. [@Tang2010]. Hamilton’s (1983)’s seminal work was the early attempt in assessing the influence of oil prices on the performance of the economy.  @Hamilton1983 study pointed out the oil-prices dynamics as a significant factor in recessions in the U.S economy after World War II. This study was followed by a series of studies to explore this relationship between oil-prices shocks and the various aspects of the aggregate economic performance of various nations. This was aggravated by oil politics and its effect on the world’s major economies in the second half twentieth century. Different transmission channels of oil prices pass through to macro-economic variables were identified. The classical supply-side affects the cost of basic inputs for production through an increase in oil prices [@barro1984]. This is the most widely accepted explanation for the question of the relationship between oil and agricultural product prices.

The cost-push inflation effect of oil price increase was discussed by many studies. A positive relationship between energy product prices and food prices, in the long run, was established in a world computable general equilibrium model by @GOHIN2010333. @Jongwanich2011 the empirical assessment of the pass-through of international food and oil prices to domestic consumer prices in nine Asian countries. Their study holds structural factors such as the economic transformation in China and India, as the major driver of increased global food and oil prices during 2007 and 2008. @Esmaeili2011 evaluated the impact of crude oil prices on world food price changes using principal component analysis (PCA). Their study explained the indirect effect of crude oil prices on food prices by the pass-through of influence of oil price index on food production index and thus on the macroeconomic index. But no direct long-run cointegration between time series prices of fuels and agricultural commodities was found by @ZHANG2018297. @Nazlioglu2012 investigated the evidence for the one-way dynamics of agricultural commodity prices and world oil prices using 24 selected commodities on their monthly prices from January 1980 to February 2010. Their empirical results of panel cointegration and Granger causality methods confirmed this strong relationship. The structural VAR model of @Wang2014 shows that during the post-crisis period (2006-2008) the influence of oil supply shock on agricultural commodity prices has increased drastically. In a panel framework, the analysis by @rezi2015 found a two-way Granger causality between crude oil prices and agricultural product prices and fertilizer prices for the period from June 1983 to June 2013. The wavelet coherence analysis of @Pal2017 found a significant trade-off between world food prices and oil prices. @tiwariAnalyzingTimefrequencyLead2018 revealed the lead-lag relationship between the energy fuels price index -and the Food price index along with other price indices. The results of wavelet coherency showed that a significant relationship exists between the fuel and food prices between the period 1990(January) to 2017(May).

The influence of changes in prices of oil products on the Chinese economy and its price transmission mechanism was evaluated by @Tang2010 using the structural vector autoregressive model. Their empirical results confirmed the positive relationship between oil prices and inflation rate and interest rate in the economy. The significant influence of expected and unexpected oil price shocks on the Chinese commodity market was showed by @ZHANG2018297. Using a structural vector autoregressive (SVAR) model, @ALIAHMED20118062 explain that the positive oil shocks hurt the level of inflation in Malaysia. @alghalithInteractionFoodPrices2010 indicated a positive relationship between food prices and oil prices for Trinidad and Tobago. They explain the potency of oil price volatility on the movement of food prices in the economy. Globally the increase in oil prices resulted in considering corn-based ethanol and soybean-based bio-diesel as alternatives for traditional crude oil. This shift resulted in a new spectrum in the importance of such grains and their prices. @Chen2010 presented the empirical evidence for the influence of crude oil prices on world prices of grains like corn and soybean, through a derived demand. Their empirical findings of the bivariate VAR-Generalized Autoregressive Conditional Heteroskedasticity (VAR-GARCH) and model from @ALMAADID20171 explain both mean and volatility spillover in the ethanol and food prices trade-off. 

The empirical results by @haixia2013 on prices of oil, corn, and ethanol in the Chinese economy also show a one-way spillover effect. They applied the EGARCH and BEKK-MVGARCH models for the period from September 2003 to August 2012. Their empirical results reveal the presence of a one-way spillover effect of oil prices on corn and ethanol prices. Various studies contradict this notion even for advanced economies like the USA. For example, @baumister2014 on US retail food price and oil prices were completely contradicting the general notion regarding the co-movement of such variables along with the conscience on cost-push food inflation by oil prices hikes. Their study explains that there is no evidence for any close influence of oil prices on US retail food prices before or after the 2006 US biofuel policies. Similarly, @gardebroek2013 also concluded the absence of any volatility spillover effect of the oil market on the corn market in the US using used the multivariate GARCH model. 

The majority of existing literature on the interrelation between energy GDP and later oil prices and GDP and other macro variables including inflation was primarily aimed at finding the presence of a long-term relationship between these variables. The basic premises of such studies were based on the usual linear cointegration models. The episodes of oil prices fall in the 1980s raised questions compatibility of such models based on the linear relationship as the macroeconomic variables followed a contradictory path. This motivated researchers to address the asymmetries in such relationships. Few studies explained the dynamic relationship between such variables in an asymmetric framework [@mork1989; @mory1993; @brown2012]. The nonlinear versions of autoregressive distributed lag (ARDL), Granger causality, and vector error correction models (VECM) models are mainly used by major studies. For example, in @lardic2008 the standard cointegration was not significant between oil prices and GDP, whereas the asymmetric cointegration between variables was found significant. The non-linear panel ARDL model estimated by @Meyer2018 for oil-exporting developing countries showed an asymmetric behavior in food prices with changes in oil prices, which was evident only in the long run absent in the short run. @Sek2019 examined the asymmetric pass-through effects of oil price changes on producer prices and consumer prices using the Nonlinear autoregressive distributed lags (NARDL) models. The study compared the behavior of this relationship in oil-importing and oil-exporting countries and found that in the former, the effect on producer prices is much larger. It was also found that for both groups of countries oil prices exerted an asymmetric impact on consumer price index (CPI) inflation. The results of @jafari2018 showed that both the positive and negative shocks of the petroleum price increase the inflation in the OPEC countries from 1990 to 2014, and to be specific the impact of the negative shocks is more than the positive shocks which indicate the asymmetric effect. 

To study asymmetric behavior in the impact of oil prices changes on domestic outputs of 7 Asian countries (Indonesia, Malaysia. Singapore, Philippines, Thailand, Japan, and Korea), @nusairolson2021 estimated a NARDL model by separating increases from decreases in oil price, which are then used to calculate partial sum processes of positive and negative oil price changes at each point in time from 1973-2018. The study concludes that the impact of movements in oil prices differs for each country depending on the direction of oil price change. In the long run, upward movement in oil prices decreases output in Japan, Korea, Malaysia, and Singapore whereas increases domestic output in Indonesia and the Philippines. The decline in prices of oil results in a significant reduction in output of Indonesia, Malaysia, and Thailand, but for Korea and the Philippines domestic output shows growth. In the case of Japan and Singapore, the long-run effect of oil price decline appears to be insignificant as in the case of Thailand for oil price hikes. The panel analysis of @Houda examined movements in food prices of the Middle East and North Africa (MENA) region in the period of 2000–2020. A negative short-term asymmetric behavior along with a positive asymmetric effect in the long-term was established by the results. The aggregated and disaggregated analyses of the impact on international food prices by the movements in the Brent and West Texas Intermediate (WTI) oil prices by @Zmami2019 confirmed asymmetric responses. The study showed that in the long run overall food prices are affected only by positive shocks on oil prices. In the linear and nonlinear autoregressive distributed lag (ARDL) models estimated for the period between January 1990 and October 2017, only the dairy price index reacted to both positive and negative changes of oil price, with greater impact of oil price hikes. @Nazlioglu2012 estimated the relationship of world oil prices on prices of corn, soybeans, and wheat using linear and nonlinear Granger causality tests.

 In the case of China, @Du2010 established the non-linear impact of world oil prices on economic growth and inflation using the multivariate vector autoregression (VAR) model. Oil price shocks in China were decomposed to supply, global demand, local demand, and oil-specific demand shock to study the time-varying effects on inflation by @chen2020. Oil-specific demand shock and domestic demand shocks emerged pivotal in the production stage and consumption stage respectively. A nonlinear autoregressive distributed lags (NARDL) model was used to analyze the oil-food prices link in Malaysia by @Ibrahim2015a. The empirical results indicate that the oil price decline was not having a significant impact on food prices while prices hike in oil markets had significant repercussions in the food market. Employing nonlinear ARDL models and nonlinear Granger causality tests, @rafiq2016 show the presence of non-linearity in the influence of oil prices on prices of twenty-five products prices for the period of 1990-2011. Similarly, @Pal2017 explained the non-linearity in the effect of diesel prices on the prices of soybean in the US. Their estimated results show that diesel prices exert higher pressure on soybean prices in higher quantiles. @Eissa2019 employed the nonlinear autoregressive distributed lag (ARDL) model of @shin2014 and the linear ARDL model of @pesaran2001 to study the long-run relationship between agricultural commodities prices and oil prices for the period of 1990-2018. Nonlinear relationships between prices of ethanol and oil were found by @Balcombe2008 in the case of Brazil using a generalized bivariate error correction model. Same way, a nonlinear relationship between energy and food prices was identified by @serra2011 for the U.S ethanol industry.
 
From 1981 to 2011, the estimated results of @Jawaid2018 indicated that positive shock in international oil price affected significantly all categories in the Consumer prices of Pakistan whereas effects of negative shock in oil prices were insignificant. using the nonlinear autoregressive distributive lag (NARDL) model @sarwar2020 confirmed this asymmetric pass-through effect of crude oil prices on food and non-food prices in Pakistan for the period 1990Q3 to 2019Q4 and pointed out that the effect of oil prices is higher on non-food inflation. For Egypt, the nonlinear ARDL model estimated by @Nasir2018 confirmed the asymmetric impacts of oil price increases and decreases on inflation for the period 1960 to 2017. In the case of Indonesia, @Prabheesh2020 found that a decline in oil prices can have a greater effect on output in the Indonesian economy than an increase in oil prices. The non-linear autoregressive distributed lag model based on quarterly data from 2000Q1 to 2019Q2 was applied to find the significant non-linear impact of oil prices on the Indonesian economy. @Goh2020 found asymmetric effects of the oil price changes on the inflation rate (producer price index) in Indonesia. The study attributes to the literature on  asymmetry in the relationship by examining the reasons behind why benefits of decreases in oil prices are not passed down to end consumers and questions the effectiveness of the inflation targeting policy. Additionally, @Baek2021 found oil price changes indeed asymmetrically affect the Indonesian rupiah in both the long and short run.

@AKINSOLA20201057 employed the panel-ARDL model to estimate the effect of real oil price on the economic growth of seven oil-importing low-income countries in sub-Saharan Africa. The results of non-linear ARDL of @shin2014 ARDL model found the absence of any significant effect of real oil price increase on real GDP per capita, while real oil price decrease has a positive effect on real GDP per capita. @Babuga2020 applied the dynamic heterogeneous nonlinear panel ARDL estimation to confirm the asymmetric impact of oil price change on inflation for Sub-Saharan Africa (SSA) countries. @Bala2018 analyzed changes in oil prices and their asymmetric effects on inflation in Algeria, Angola, Libya, and Nigeria using 3 different oil price data. Results of dynamic panels of Autoregressive distributed lag (ARDL) showed that even though both upward and downward movements in oil prices had a positive impact on inflation, the impact was more significant when oil prices decreased. @LACHEHEB2019217 studied the relationship between oil prices and inflation in Algeria using forty-five years’ data at the annual frequency and concluded that the relationship is asymmetric. An increase in oil prices leads to an increase in price level whereas the impact of the decrease in oil price is insignificant. @Shitile2020 attempted to relate oil prices with sub-indices of the consumer price index of Nigeria to study the asymmetric impact of oil price shocks on the economy in the long run. The NARDL models revealed that in the occurrence of a positive or negative unitary oil price shock, a period of 4-8 quarters is expected for the convergence of disaggregated inflation to its long-run equilibrium. In the case of Ghana, @Ayisi2021 found the asymmetric impact of oil prices on Inflation only in the long run, not significant in the short run. The findings are critical for Ghana as the country recently adopted the automatic adjustment system for petroleum prices from the regulating model.

There are few notable studies about the co-movement of oil prices, inflation, and output in India. Studies specific for examining the impact of oil prices on the dynamics of food prices in the Indian market are limited. These studies have shown the presence of linear and nonlinear relationships between the variables. Bidirectional causality between oil and non-oil inflation is found by @Bhattacharya2001 using a multivariate VAR model based on monthly data from April 1994 to December 2000. Their empirical findings show that a positive oil shock results in an increase in inflation and a decrease in output. This stagflation induced by oil price shock in the Indian economy is also examined by @kar2005. They further stated that the deceleration of growth as the effect of oil price shocks is presented in long run. Industrial growth and the effects of oil price shocks are examined by @Kumar2009 between 1975 and 2004. The empirical results of the multivariate VAR model specified the negative effect of oil price shocks on the growth of industrial production. A sector-wise analysis of Kar and @kar2011 stated that the fluctuations in oil prices affect agricultural and tertiary sectors more and the impact of oil price shocks on such sectors is long-run. According to @Bhattacharya2001, the role of administrated prices and the lag in their price adjustments has produced bigger shocks in the economy. Different macroeconomic indicators of the Indian economy like output growth, inflation, etc. are studied based on the effects of international oil price shocks on them by @Das2014. Their study found a differential impact on these variables and further examined these impacts along with different levels of pass-through. Their results presented two scenarios: partial pass-through and full pass-through of international oil price shocks. In the former case, a 10 percent rise can bring a 0.3 percent rise in inflation whereas and if it is full pass-through then it would result in a 0.6 percent increase in inflation.

In the commodity-wise study about the causal factors of food prices inflation in India,@Nair2012 found that in the period from March 2008 to November 2008 and January 2010 to July 2010, the surge in international oil prices is transmitted to wholesale price index (WPI) inflation rate of mineral oil. @alom2013 examined the dynamics of world oil prices and food prices on a few Asian and Pacific economies. The basic premise is that the characteristics of a particular economy will be the deciding factor in the magnitude of the effects of external price shocks. The structural vector autoregression (SVAR) models concluded that in the Indian economy, the impact of world oil price shocks is comparatively lesser than the impact of food price shocks. The multivariate vector autoregression (VAR) model applied by @Bhat2014 confirmed the asymmetric nature of the influence of oil price shocks on the Indian economy. Their study explains the exogenous nature of macro-economic movement in India to oil price changes for the period April 1992 to August 2013. @Mohanty2015 identified crude oil prices as one of the major determining factors of inflation level in the Indian market. They used quarterly data based Structural vector autoregression (SVAR) model which indicated that in the period 2009–2010 and most of 2010–2011, changes in world oil prices determined inflation level in India with an impact of above 20 percent and later after 2011-2013 below 20 percent. In the transmission channel of crude oil prices and oil product prices, asymmetry was also found by @Pal2016. They applied multiple threshold nonlinear autoregressive distributed lag (MTNARDL) model to decompose the price changes of crude oil holding multiple thresholds and confirm that the asymmetric price transmission, oil product prices move together with crude oil prices when it goes up, but fail to follow when there is a significant fall in crude prices. @Ahmed2019 applied Structural Vector Autoregressive (SVAR) model to examine how oil price shocks affect the inflation of five SAARC countries including India. Their empirical results confirm that the variables are cointegrated having a long-run relationship. The empirical results of the Structural vector autoregression (SVAR) model applied by @Bhat2018 also concluded the asymmetric impact of oil price shocks on output in the economy where price inflexibility or inflation rigidity is evident even in the long run (April 1994 to May 2016). Their findings confirm that energy price (oil price) has a significant impact on food prices. For 8 Asian countries including India. @Taghizadeh-Hesary2019 estimated a Panel VAR model revealed a positive relation between biofuel price and food price where the impulse response function results showed that any shock from oil price resulted in a positive response from the agricultural food prices. The conclusion of analysis based on the time-varying structural vector autoregressive (TV-SVA) model of @Nasir2018 was on the vulnerability of the Indian economy to the changes in oil prices in terms of their adverse effects on GDP, inflation, and balance of trade.

Using the quantile Granger causality test Wei @Su2021 found asymmetric behavior in the causal relationship between the crude oil price shocks and Economic Policy Uncertainty in BRICS countries. The study also concludes that the positive effect of the crude oil price on economic policy uncertainty is significant in India along with China and Brazil. high dependence on oil plays a detriminal role in this aspect. @Zakaria2021 reveal that the impact of oil price change on inflation are asymmetric in South Asian countries (. India, Bangladesh, Pakistan, and Sri Lanka) in the long run, and the positive oil price changes have a stronger effect on inflation rates than negative oil price changes in the period from 1980 (January) to 2018 (December).  @sarmah2021 used both the structural vector autoregressive model and the nonlinear autoregressive distribution lag model to study the effects of changes in crude oil prices on the Inflation and economic growth rate of India for the period from 1997 (April) to 2016 (July). The former showed that results as the crude oil price has a positive impact on the rate of inflation whereas an inverse relation exists between crude oil price and economic growth. For the NARDL model, crude oil price movements were separated into positive and negative partial sum and the estimated results were comparable in the case of positive partial sum of oil price on inflation and growth rates, where it was contradicting for negative partial sum of crude oil price and growth rate.
